# Generated by Django 4.2.6 on 2024-06-17 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryPassagingCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('number', models.CharField(verbose_name='Номерной знак')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_model.carmodel', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Запись проезда автомобили',
                'verbose_name_plural': 'История проезжающих автомобилей',
                'unique_together': {('datetime', 'number', 'model')},
            },
        ),
    ]
